import type { Metadata } from "next";
import { Manrope, Newsreader } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import "../styles/style.css";
import { ThemeProvider } from "@/components/theme-provider";

const manrope = Manrope({
  variable: "--font-sans",
  subsets: ["latin"],
});

const newsreader = Newsreader({
  variable: "--font-serif",
  subsets: ["latin"],
});

const menlo = localFont({
  src: [
    {
      path: "./fonts/Menlo-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Menlo-Bold.ttf",
      weight: "700",
      style: "bold",
    },
  ],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${manrope.variable} ${menlo.variable} ${newsreader.variable} antialiased font-sans`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          forcedTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
